"""add job upload_path for two-phase review pipeline

Revision ID: 0cdfed529c48
Revises: 8f0d5ed871f0
Create Date: 2026-09-07 04:49:26.337850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdfed529c48'
down_revision = '8f0d5ed871f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('upload_path')

    # ### end Alembic commands ###
