"""track real llm translation cost per job

Revision ID: 84ce1df9e6ce
Revises: f2e908097a94
Create Date: 2026-09-08 13:52:57.331461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ce1df9e6ce'
down_revision = 'f2e908097a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translate_prompt_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('translate_completion_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('translate_cost_usd', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('translate_cost_usd')
        batch_op.drop_column('translate_completion_tokens')
        batch_op.drop_column('translate_prompt_tokens')

    # ### end Alembic commands ###
