"""persist phase2 tts/subtitle choices on job for continue endpoint

Revision ID: 9cddda4d3fb6
Revises: 0cdfed529c48
Create Date: 2026-09-07 05:00:22.623720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cddda4d3fb6'
down_revision = '0cdfed529c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tts_voice', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('original_volume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('subtitle_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('subtitle_mode')
        batch_op.drop_column('original_volume')
        batch_op.drop_column('tts_voice')

    # ### end Alembic commands ###
