"""add user notify_email preference

Revision ID: f2e908097a94
Revises: 9cddda4d3fb6
Create Date: 2026-09-07 13:43:06.778964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e908097a94'
down_revision = '9cddda4d3fb6'
branch_labels = None
depends_on = None


def upgrade():
    # Tu dong sinh ra sa.text('1') vi autogenerate chay tren SQLite (dung
    # de kiem thu migration) — SQLite bieu dien boolean bang 0/1, nhung
    # Postgres (production, xem README) KHONG tu ep integer sang boolean o
    # server_default, se loi that. Sua tay thanh 'true' nhu is_active/edited
    # o cac migration truoc, chay dung tren ca hai.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_email', sa.Boolean(), server_default=sa.text('true'), nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notify_email')

    # ### end Alembic commands ###
